# Generated by Django 4.2.4 on 2023-08-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptions', '0002_rename_descriptions_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
