# Generated by Django 4.2.4 on 2023-08-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptions', '0003_description_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
